version: '3.7'

services:
  unit:
    image: asteria-proxy:app
    build:
      context: .
      target: pre-builder
    env_file: configs/env/base.env
    entrypoint: go test -v ./...
    volumes:
      - .:/go/src/github.com/steve-nzr/asteria-proxy
