version: '3.7'

services:
  app:
    image: asteria-proxy:app
    build:
      context: .
      target: pre-builder
    tty: true
    env_file: configs/env/base.env
    depends_on:
      - rabbitmq
    ports:
      - 23000:23000
    volumes:
      - .:/go/src/github.com/steve-nzr/asteria-proxy

  # rabbitmq:
  #   image: rabbitmq:3-alpine

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 15672:15672
